### PR TITLE
Fix issue #2 on duplicate posts

### PR DESCRIPTION
**Pull request by fullbright**
Compair the slug from github with the one stored in wordpress post meta.

### CODE REVIEW

**Comment by fullbright** [comment]
Fix the issue #8 for myself. Wanted to share it.

**Comment by lukaszpiotrluczak** [comment]
@vaakash this PR contains some good ideas. Maybe I can resolve conflicts and polish it so that this changes can be included in next release?

**Comment by vaakash** [comment]
@lukaszpiotrluczak Sure, please do submit PR. Uploading featured image is one of the requested featured. I believe that is the only feature which can be pulled from this PR.

**Comment by fullbright** [comment]
Merge has been done. I couldn't test. If some one can help with testing, that would be nice.

**Comment by vaakash** [comment]
Hi @fullbright, Thanks for the changes. The issue where duplicate posts were published is addressed in v1.4 - https://github.com/vaakash/git-it-write/releases/tag/v1.4 already.

Also, this PR is lagging behind. I think we can close this PR and review a fresh one.

For the changes related to uploading featured image, can you please submit a new PR?

**Comment by lukaszpiotrluczak** [comment]
Hi @fullbright, 
I also think we could close this PR. 
If you want to provide a new PR with featured image then great! And if you don't want to then I can provide it.
Just please give a note.
Best regards
Łukasz

**Comment by fullbright** [comment]
Hello,

Sorry for the late reply.
Okay. I let you provide it. My idea was to provide a way to set the image
from an external url, as well as with an image in the repo.

Thank you.

**Pull request closed without merging**
